### ISSUE TITLE
kaldi-native-fbank usage in iOS

### ISSUE THREAD

**Issue by dhtheuno** [csukuangfj/kaldi-native-fbank#56]
If I want to use the kaldi-native-fbank functions on iOS, is it sufficient to compile them with the iOS toolchain and then use them? I successfully compiled them and created an xcframework, but Xcode was still unable to recognize some of the standard library components in the header files. Do I need to wrap these functions with another header file to make them accessible on iOS?
Thank you so much for your repository and your valuable help! 🙏

**Comment by csukuangfj** [comment]
this repo provides only c/c++ apis.

If you want to use it in iOS, it is your responsibility to
 - build it for iOS
 - provide either objective c or swift binding for it

this repo is not special. as long as you have wrapped some c/c++ code to iOS, then it is super easy for you.

Otherwise, you have to spend lots of time to find out how to do that.

we have already used it in sherpa-onnx and sherpa-ncnn, which supports iOS.
